# TODO: Enable when warnings are to be fixed.
AllCops:
  DisabledByDefault: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/HeredocIndentation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true

Style/SignalException:
  Enabled: true
  EnforcedStyle: only_raise

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Style/IfUnlessModifier:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19

Layout/SpaceAfterComma:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

# inherit_from: .rubocop_todo.yml
