# TODO: Enable when warnings are to be fixed.
AllCops:
  DisabledByDefault: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

# inherit_from: .rubocop_todo.yml
