# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rbvmomi}
  s.version = "1.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rich Lane"]
  s.date = %q{2012-05-07}
  s.default_executable = %q{rbvmomish}
  s.email = %q{rlane@vmware.com}
  s.executables = ["rbvmomish"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".yardopts",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/rbvmomish",
    "devel/analyze-vim-declarations.rb",
    "devel/analyze-xml.rb",
    "devel/benchmark.rb",
    "devel/collisions.rb",
    "devel/merge-internal-vmodl.rb",
    "examples/annotate.rb",
    "examples/clone_vm.rb",
    "examples/create_vm-1.9.rb",
    "examples/create_vm.rb",
    "examples/extraConfig.rb",
    "examples/logbundle.rb",
    "examples/logtail.rb",
    "examples/nfs_datastore.rb",
    "examples/power.rb",
    "examples/readme-1.rb",
    "examples/readme-2.rb",
    "examples/run.sh",
    "examples/screenshot.rb",
    "examples/vdf.rb",
    "examples/vm_drs_behavior.rb",
    "lib/rbvmomi.rb",
    "lib/rbvmomi/basic_types.rb",
    "lib/rbvmomi/connection.rb",
    "lib/rbvmomi/deserialization.rb",
    "lib/rbvmomi/fault.rb",
    "lib/rbvmomi/trivial_soap.rb",
    "lib/rbvmomi/trollop.rb",
    "lib/rbvmomi/type_loader.rb",
    "lib/rbvmomi/vim.rb",
    "lib/rbvmomi/vim/ComputeResource.rb",
    "lib/rbvmomi/vim/Datacenter.rb",
    "lib/rbvmomi/vim/Datastore.rb",
    "lib/rbvmomi/vim/DynamicTypeMgrAllTypeInfo.rb",
    "lib/rbvmomi/vim/DynamicTypeMgrDataTypeInfo.rb",
    "lib/rbvmomi/vim/DynamicTypeMgrManagedTypeInfo.rb",
    "lib/rbvmomi/vim/Folder.rb",
    "lib/rbvmomi/vim/HostSystem.rb",
    "lib/rbvmomi/vim/ManagedEntity.rb",
    "lib/rbvmomi/vim/ManagedObject.rb",
    "lib/rbvmomi/vim/ObjectContent.rb",
    "lib/rbvmomi/vim/ObjectUpdate.rb",
    "lib/rbvmomi/vim/OvfManager.rb",
    "lib/rbvmomi/vim/PropertyCollector.rb",
    "lib/rbvmomi/vim/ReflectManagedMethodExecuter.rb",
    "lib/rbvmomi/vim/ResourcePool.rb",
    "lib/rbvmomi/vim/ServiceInstance.rb",
    "lib/rbvmomi/vim/Task.rb",
    "lib/rbvmomi/vim/VirtualMachine.rb",
    "test/test_deserialization.rb",
    "test/test_emit_request.rb",
    "test/test_exceptions.rb",
    "test/test_helper.rb",
    "test/test_misc.rb",
    "test/test_parse_response.rb",
    "test/test_serialization.rb",
    "vmodl.db"
  ]
  s.homepage = %q{https://github.com/rlane/rbvmomi}
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.8.7")
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Ruby interface to the VMware vSphere API}

  s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
  s.add_dependency(%q<builder>, [">= 0"])
  s.add_dependency(%q<trollop>, [">= 0"])
  s.add_dependency('excon')
end

