#!/usr/bin/env ruby
require 'rbvmomi'
include RbVmomi

vim = RbVmomi.connect ENV['RBVMOMI_URI']

rootFolder = vim.serviceInstance.RetrieveServiceContent!.rootFolder

dc = rootFolder.childEntity.first
vmFolder = dc.vmFolder
vms = vmFolder.childEntity

vms.select { |vm| vm.runtime.powerState == 'poweredOn' }.each { |vm| puts "powering off #{vm}"; vm.PowerOffVM_Task!.wait_task }
vms.each { |vm| puts "destroying #{vm}"; vm.Destroy_Task!.wait_task }
