#!/usr/bin/env ruby
require 'rbvmomi'
include RbVmomi

fail "must set RBVMOMI_URI" unless ENV['RBVMOMI_URI']

soap = Soap.new URI.parse(ENV['RBVMOMI_URI'])
soap.debug = false
$profile = false

si = soap.serviceInstance
sm = si.RetrieveServiceContent!.sessionManager
sm.Login! :userName => 'root', :password => ''

rootFolder = si.RetrieveServiceContent!.rootFolder

dc = rootFolder.childEntity.first
vmFolder = dc.vmFolder
vms = vmFolder.childEntity

vms.select { |vm| vm.runtime.powerState == 'poweredOn' }.each { |vm| puts "powering off #{vm}"; vm.PowerOffVM_Task!.wait_task }
vms.each { |vm| puts "destroying #{vm}"; vm.Destroy_Task!.wait_task }
