#!/usr/bin/env ruby
require 'rbvmomi'
include RbVmomi

vim = RbVmomi.connect ENV['RBVMOMI_URI']

rootFolder = vim.serviceInstance.RetrieveServiceContent!.rootFolder

dc = rootFolder.childEntity.first
vmFolder = dc.vmFolder
vms = vmFolder.childEntity

vms.each do |vm|
  summary = vm.summary
  puts "#{vm.value} #{summary.config.name} #{summary.runtime.powerState}"
end
