name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Run RuboCop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop
