name: Test

on: [push, pull_request]

jobs:
  test:
    name: Run test-unit
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [2.5, 2.6, 2.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake
